from ..models import Actividad

class GestorActividad():

    def __init__(self, gestor_docente, actividad_DAO):
        self.gestor_docente = gestor_docente
        self.actividad_DAO = actividad_DAO
    
    def alta_actividad(self, actividad_DTO, docente_DTO):
        docente = self.gestor_docente.alta_docente(docente_DTO)
        actividad = Actividad(id_actividad=actividad_DTO.get_id_actividad(), nombre=actividad_DTO.get_nombre(), descripcion=actividad_DTO.get_descripcion(), docente=docente, activo=True, fecha_baja=None)
        return actividad

    def obtener_actividades(self):
        actividades = [
            Actividad(id_actividad=1, nombre="Análisis Matemático I", 
                    descripcion="Primera materia de cálculo. Se enseñan funciones, límites, derivadas, integrales y series."),
            Actividad(id_actividad=2, nombre="Álgebra y Geometría Analítica", 
                    descripcion="Se enseñan sistemas de funciones, matrices, determinantes, rectas, planos, transformaciones, subespacios vectoriales y cónicas."),
            Actividad(id_actividad=3, nombre="Física I", 
                    descripcion="Mecánica clásica. Se enseñan distintos tipos de movimientos, óptica, ondas, etc."),
            Actividad(id_actividad=4, nombre="Inglés I", 
                    descripcion="Primera materia inglés."),
            Actividad(id_actividad=5, nombre="Química", 
                    descripcion="Se enseñan conceptos básicos de química, reacciones químicas, estequiometría, etc."),
            Actividad(id_actividad=6, nombre="Sistemas de Representación", 
                    descripcion="Se enseñan técnicas de dibujo técnico y representación gráfica."),
            Actividad(id_actividad=7, nombre="Análisis Matemático II", 
                    descripcion="Segunda materia de cálculo. Se enseñan funciones de varias variables, integrales múltiples, etc."),
            Actividad(id_actividad=8, nombre="Física II", 
                    descripcion="Electromagnetismo. Se enseñan campos eléctricos y magnéticos, circuitos eléctricos, etc."),
            Actividad(id_actividad=9, nombre="Inglés II", 
                    descripcion="Segunda materia de inglés."),
            Actividad(id_actividad=10, nombre="Probabilidad y Estadística", 
                    descripcion="Se enseñan conceptos de probabilidad, variables aleatorias, distribuciones, inferencia estadística, etc."),
            Actividad(id_actividad=11, nombre="Análisis de Sistemas", 
                    descripcion="Se enseñan técnicas de análisis de sistemas de información, modelado de procesos, etc."),
            Actividad(id_actividad=12, nombre="Algoritmos y Estructuras de Datos", 
                    descripcion="Se enseñan técnicas de programación, estructuras de datos, algoritmos de ordenamiento y búsqueda, etc."),
            Actividad(id_actividad=13, nombre="Arquitectura de Computadoras", 
                    descripcion="Se enseñan conceptos de arquitectura de computadoras, ensamblador, etc."),
            Actividad(id_actividad=14, nombre="Matemática Discreta", 
                    descripcion="Se enseñan conceptos de lógica, teoría de conjuntos, grafos, etc."),
            Actividad(id_actividad=15, nombre="Economía", 
                    descripcion="Se enseñan conceptos básicos de economía, microeconomía, macroeconomía, etc."),
            Actividad(id_actividad=16, nombre="Gestión de Datos", 
                    descripcion="Se enseñan técnicas de modelado de datos, bases de datos relacionales, SQL, etc."),
            Actividad(id_actividad=17, nombre="Ingeniería de Software I", 
                    descripcion="Se enseñan técnicas de desarrollo de software, ciclo de vida del software, etc."),
            Actividad(id_actividad=18, nombre="Redes de Computadoras", 
                    descripcion="Se enseñan conceptos de redes de computadoras, protocolos, arquitectura de redes, etc."),
            Actividad(id_actividad=19, nombre="Teoría de Control", 
                    descripcion="Se enseñan conceptos de sistemas de control, retroalimentación, estabilidad, etc."),
            Actividad(id_actividad=20, nombre="Investigación Operativa", 
                    descripcion="Se enseñan técnicas de optimización, programación lineal, teoría de colas, etc."),
            Actividad(id_actividad=21, nombre="Ingeniería de Software II", 
                    descripcion="Se enseñan técnicas avanzadas de desarrollo de software, metodologías ágiles, etc."),
            Actividad(id_actividad=22, nombre="Sistemas de Información I", 
                    descripcion="Se enseñan conceptos de sistemas de información, ERP, CRM, etc."),
            Actividad(id_actividad=23, nombre="Administración de Recursos", 
                    descripcion="Se enseñan técnicas de administración de recursos humanos, financieros, etc."),
            Actividad(id_actividad=24, nombre="Sistemas de Información II", 
                    descripcion="Se enseñan técnicas avanzadas de sistemas de información, BI, Big Data, etc."),
            Actividad(id_actividad=25, nombre="Inteligencia Artificial", 
                    descripcion="Se enseñan conceptos de inteligencia artificial, machine learning, redes neuronales, etc."),
            Actividad(id_actividad=26, nombre="Simulación", 
                    descripcion="Se enseñan técnicas de simulación de sistemas, modelado de eventos discretos, etc."),
            Actividad(id_actividad=27, nombre="Seguridad Informática", 
                    descripcion="Se enseñan conceptos de seguridad informática, criptografía, seguridad en redes, etc."),
            Actividad(id_actividad=28, nombre="Gestión de Proyectos", 
                    descripcion="Se enseñan técnicas de gestión de proyectos, planificación, control, etc."),
            Actividad(id_actividad=29, nombre="Auditoría de Sistemas", 
                    descripcion="Se enseñan técnicas de auditoría de sistemas, control interno, etc."),
            Actividad(id_actividad=30, nombre="Derecho Informático", 
                    descripcion="Se enseñan conceptos de derecho informático, propiedad intelectual, protección de datos, etc."),
            Actividad(id_actividad=31, nombre="Taller de Programación I", 
                    descripcion="Se enseñan técnicas de programación avanzada, desarrollo de aplicaciones, etc."),
            Actividad(id_actividad=32, nombre="Taller de Programación II", 
                    descripcion="Se enseñan técnicas avanzadas de programación, desarrollo de aplicaciones complejas, etc."),
            Actividad(id_actividad=33, nombre="Taller de Programación III", 
                    descripcion="Se enseñan técnicas de programación en equipo, desarrollo de proyectos, etc."),
            Actividad(id_actividad=34, nombre="Taller de Programación IV", 
                    descripcion="Se enseñan técnicas avanzadas de programación en equipo, desarrollo de proyectos complejos, etc."),
            Actividad(id_actividad=35, nombre="Taller de Programación V", 
                    descripcion="Se enseñan técnicas de programación en equipo, desarrollo de proyectos de gran escala, etc."),
            Actividad(id_actividad=36, nombre="Taller de Programación VI", 
                    descripcion="Se enseñan técnicas avanzadas de programación en equipo, desarrollo de proyectos de gran escala, etc."),
            Actividad(id_actividad=37, nombre="Redes y Comunicaciones", 
                    descripcion="Se enseñan conceptos de redes y comunicaciones, protocolos, arquitectura de redes, etc."),
            Actividad(id_actividad=38, nombre="Bases de Datos", 
                    descripcion="Se enseñan técnicas de diseño y administración de bases de datos, SQL, etc."),
            Actividad(id_actividad=39, nombre="Ingeniería de Requisitos", 
                    descripcion="Se enseñan técnicas de ingeniería de requisitos, análisis y especificación de requisitos, etc."),
            Actividad(id_actividad=40, nombre="Desarrollo de Software", 
                    descripcion="Se enseñan técnicas de desarrollo de software, metodologías ágiles, etc."),
            Actividad(id_actividad=41, nombre="Calidad de Software", 
                    descripcion="Se enseñan técnicas de aseguramiento de la calidad del software, pruebas, etc."),
            Actividad(id_actividad=42, nombre="Arquitectura de Software", 
                    descripcion="Se enseñan conceptos de arquitectura de software, patrones de diseño, etc."),
            Actividad(id_actividad=43, nombre="Gestión de Configuración", 
                    descripcion="Se enseñan técnicas de gestión de configuración de software, control de versiones, etc."),
            Actividad(id_actividad=44, nombre="Desarrollo Web", 
                    descripcion="Se enseñan técnicas de desarrollo web, HTML, CSS, JavaScript, etc."),
            Actividad(id_actividad=45, nombre="Desarrollo Móvil", 
                    descripcion="Se enseñan técnicas de desarrollo de aplicaciones móviles, Android, iOS, etc."),
            Actividad(id_actividad=46, nombre="Computación en la Nube", 
                    descripcion="Se enseñan conceptos de computación en la nube, servicios en la nube, etc."),
            Actividad(id_actividad=47, nombre="Big Data", 
                    descripcion="Se enseñan técnicas de análisis de grandes volúmenes de datos, Hadoop, Spark, etc."),
            Actividad(id_actividad=48, nombre="Machine Learning", 
                    descripcion="Se enseñan técnicas de machine learning, algoritmos de aprendizaje supervisado y no supervisado, etc."),
            Actividad(id_actividad=49, nombre="Internet de las Cosas", 
                    descripcion="Se enseñan conceptos de Internet de las Cosas, dispositivos conectados, etc."),
            Actividad(id_actividad=50, nombre="Sistemas Operativos", 
                    descripcion="Se estudian conceptos de procesos, memoria, sistemas de archivos y concurrencia.")
        ]
        return actividades