# Generated by Django 5.1.2 on 2024-12-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.BinaryField(max_length=60),
        ),
    ]
