# Generated by Django 5.1.2 on 2024-12-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0002_alter_usuario_contrasenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='id_tipo_actividad',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='id_docente',
            new_name='docente',
        ),
        migrations.DeleteModel(
            name='TipoActividad',
        ),
    ]
