# Generated by Django 5.1.2 on 2024-12-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0002_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='tiene_pizarrones',
            new_name='pizarrones',
        ),
        migrations.RenameField(
            model_name='tiene',
            old_name='nro_aula',
            new_name='aula',
        ),
        migrations.RenameField(
            model_name='tiene',
            old_name='id_tipo_pizarron',
            new_name='tipo_pizarron',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='bedel',
            field=models.ForeignKey(db_column='id_bedel', default='utn-000010', on_delete=django.db.models.deletion.PROTECT, to='tpdisenio.bedel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiene',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
