# Generated by Django 5.1.2 on 2024-10-17 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0002_remove_administrador_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulainformatica',
            name='nro_aula',
        ),
        migrations.RemoveField(
            model_name='aulamultimedios',
            name='nro_aula',
        ),
        migrations.RemoveField(
            model_name='aulasinrecursosadicionales',
            name='nro_aula',
        ),
        migrations.AddField(
            model_name='aulainformatica',
            name='aula_ptr',
            field=models.OneToOneField(db_column='nro_aula', default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpdisenio.aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aulamultimedios',
            name='aula_ptr',
            field=models.OneToOneField(db_column='nro_aula', default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpdisenio.aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aulasinrecursosadicionales',
            name='aula_ptr',
            field=models.OneToOneField(db_column='nro_aula', default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tpdisenio.aula'),
            preserve_default=False,
        ),
    ]
