# Generated by Django 5.1.2 on 2024-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0003_remove_actividad_id_tipo_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
