# Generated by Django 5.1.2 on 2024-10-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0003_remove_aulainformatica_nro_aula_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sesion',
        ),
    ]
