# Generated by Django 5.1.2 on 2024-12-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0004_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AulaMultimedios',
            new_name='AulaMultimedio',
        ),
        migrations.AlterModelTable(
            name='aulamultimedio',
            table='AulaMultimedio',
        ),
    ]
