# Generated by Django 5.1.2 on 2024-11-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0004_delete_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateField(blank=True, default=None),
        ),
    ]
