# Generated by Django 5.1.2 on 2024-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpdisenio', '0005_usuario_activo_usuario_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
