from .Actividad import Actividad
from .Administrador import Administrador
from .Aula import Aula
from .AulaInformatica import AulaInformatica
from .AulaMultimedios import AulaMultimedios
from .AulaSinRecursosAdicionales import AulaSinRecursosAdicionales
from .Bedel import Bedel
from .Docente import Docente
from .Periodo import Periodo
from .Reserva import Reserva
from .Reservacion import Reservacion
from .TipoActividad import TipoActividad
from .TipoPizarron import TipoPizarron
from .Usuario import Usuario
